<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LameDuck" targetNamespace="http://lameduck.group8.ws.dtu"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://lameduck.group8.ws.dtu" xmlns:ns="http://types.lameduck.group8.ws.dtu" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://lameduck.group8.ws.dtu">
            <xsd:import namespace="http://types.lameduck.group8.ws.dtu" schemaLocation="LameDuckSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="LameDuckRequest">
        <part name="input" type="ns:getFlightRequestType"/>
    </message>
    <message name="LameDuckResponse">
        <part name="output" type="ns:flightInfoListType"/>
    </message>
    <portType name="LameDuckPortType">
        <operation name="LameDuck">
            <input name="input1" message="tns:LameDuckRequest"/>
            <output name="output1" message="tns:LameDuckResponse"/>
        </operation>
    </portType>
    <binding name="LameDuckPortTypeBinding" type="tns:LameDuckPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="LameDuck">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="LameDuckService">
        <port name="LameDuckPortTypeBindingPort" binding="tns:LameDuckPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service"/>
        </port>
    </service>
</definitions>
